service: express-s3-upload

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-west-1
  environment:
    BUCKET: ${env:BUCKET}
    AWS_REGION: ${env:AWS_REGION}
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}

functions:
  app:
    handler: app.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: '{proxy+}'
          method: ANY   
plugins:
  - serverless-offline
